django_to_do/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todoapp.urls')),
    path('users/', include('users.urls')),
    # path('users/', include('django.contrib.auth.urls')),
]

todoapp/urls.py
from django.urls import path
from . import views

app_name = 'todoapp'
urlpatterns = [
    path('', views.index, name='index'),
    path('list/', views.todo_list, name='list'),
    path('add/', views.add_todo, name='add'),
    path('delete/<int:todo_id>/', views.delete_todo, name='delete'),
    path('finish/<int:todo_id>/', views.finish_todo, name='finish'),
    path('search/', views.search_todo, name='search'),
]

users/urls.py
from django.urls import path

from . import views

app_name = 'users'
urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('signup/', views.SignUpView.as_view(), name='signup'),
]

todoapp/models.py
from django.db import models
from django.conf import settings


# Create your models here.
class Todo(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,)
    text = models.CharField(max_length=128, null=False, help_text="This field is required.",)
    added_date = models.DateTimeField(auto_now_add=True)
    done = models.BooleanField(default=False)

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class CustomUser(AbstractUser):
    pass

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):

    class Meta:
        model = CustomUser
        fields = UserCreationForm.Meta.fields

todoapp/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse

from .models import Todo


# Create your views here.
def index(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse("todoapp:list"))
    else:
        return render(request, 'todoapp/index.html')


@login_required
def todo_list(request):
    todo_items = Todo.objects.filter(user=request.user, done=False).order_by('-added_date')
    completed_items = Todo.objects.filter(user=request.user, done=True).order_by('-added_date')
    return render(request, 'todoapp/list.html', {
        "todo_items": todo_items,
        "completed_times": completed_items,
    })


def add_todo(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("users:login"))
    if request.POST["content"].split():
        Todo.objects.create(user=request.user, text=request.POST["content"])
    return HttpResponseRedirect(reverse("todoapp:list"))


def delete_todo(request, todo_id):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("users:login"))
    Todo.objects.get(id=todo_id).delete()
    return HttpResponseRedirect(reverse("todoapp:list"))


def finish_todo(request, todo_id):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("users:login"))
    finished_todo = Todo.objects.get(id=todo_id)
    finished_todo.done = True
    finished_todo.save()
    return HttpResponseRedirect(reverse("todoapp:list"))


@login_required
def search_todo(request):
    if request.GET:  # what if access search view via GET method
        query_string = request.GET["search"]
        found_tasks = set()
        if query_string.split():  # what if the content in queryText makes sense
            query_string_list = query_string.split()
            for string in query_string_list:
                for result in Todo.objects.filter(text__icontains=string):
                    found_tasks.add(result)
        else:  # if the content does not make sense, list all tasks
            found_tasks = Todo.objects.all()
        return render(request, 'todoapp/result.html', {
            "query_string": query_string,
            "found_tasks": found_tasks,
        })
    else:
        return HttpResponseRedirect(reverse("todoapp:list"))

users/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView
from django.contrib.auth import views as auth_views


from .forms import CustomUserCreationForm


class LoginView(auth_views.LoginView):
    template_name = 'users/login.html'


class LogoutView(auth_views.LogoutView):
    next_page = '/'


class SignUpView(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('users:login')
    template_name = 'users/signup.html'

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-dark bg-dark justify-content-between">
        <!-- Navbar content -->
            <a class="navbar-brand" href="{% url 'todoapp:index' %}">To-do App</a>

            {% if user.is_authenticated %}
                <span class="navbar-nav">
                    <a class="btn btn-outline-secondary" href="{% url 'users:logout' %}" role="button">Log out</a>
                </span>
            {% endif %}

        </nav>
    </header>

    <!-- Main page content -->
    <main role="main" class="container">
        {% block content %}{% endblock %}
    </main>

</body>
</html>

templates/bs4_form.html
{% load widget_tweaks %}

{% for hidden_field in form.hidden_fields %}
    {{ hidden_field }}
{% endfor %}

{% if form.non_field_errors %}
    <div class="alert alert-danger" role="alert">
        {% for error in form.non_field_errors %}
            {{ error }}
        {% endfor %}
    </div>
{% endif %}

{% for field in form.visible_fields %}
    <div class="form-group">
        {{ field.label_tag }}

        {% if form.is_bound %}
            {% if field.errors %}
                {% render_field field class="form-control is-invalid" %}
                {% for error in field.errors %}
                    <div class="invalid-feedback">
                        {{ error }}
                    </div>
                {% endfor %}
            {% else %}
                {% render_field field class="form-control is-valid" %}
            {% endif %}
        {% else %}
            {% render_field field class="form-control" %}
        {% endif %}

    {% if field.help_text %}
        <small class="form-text text-muted">{{ field.help_text }}</small>
    {% endif %}
    </div>
{% endfor %}

todoapp/templates/todoapp/index.html
{% extends 'base.html' %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}Django To-do App{% endblock %}
</head>
<body>
    {% block content %}
        <div class="row mt-4">
            <div class="mx-auto">
                <h2>Welcome to Django to-do app!</h2>

                {% if user.is_authenticated %}
                    <p>
                        Hi, {{ user.username }}. You are logged in.
                        <a href="{% url 'users:logout' %}">Log out</a>
                    </p>
                {% else %}
                    <p>You are not logged in. <a href="{% url 'users:login' %}">Sign in</a></p>
                    <p>If you don't have an account, please <a href="{% url 'users:signup' %}">sign up</a></p>
                {% endif %}
            </div>
        </div>
    {% endblock %}
</body>
</html>

todoapp/templates/todoapp/list.html
{% extends 'base.html' %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}To-do List{% endblock %}
</head>
<body>
    {% block content %}
        <div class="row mt-4">
            <div class="col d-flex justify-content-between">
                <h2>Hi, {{ user.get_username }}</h2>
                <div class="d-flex">
                    <div class="btn-group mr-2">
                        <button type="button" class="btn btn-outline-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <svg class="bi bi-file-plus" width="1.5em" height="1.5em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                <path d="M9 1H4a2 2 0 0 0-2 2v10a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2V8h-1v5a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V3a1 1 0 0 1 1-1h5V1z"/>
                                <path fill-rule="evenodd" d="M13.5 1a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1H13V1.5a.5.5 0 0 1 .5-.5z"/>
                                <path fill-rule="evenodd" d="M13 3.5a.5.5 0 0 1 .5-.5h2a.5.5 0 0 1 0 1H14v1.5a.5.5 0 0 1-1 0v-2z"/>
                            </svg>
                        </button>
                        <form class="dropdown-menu p-3 dropdown-menu-right" style="width: 300px;" action="{% url 'todoapp:add' %}" method="post">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="newTask">Add a new task</label>
                                <input type="text" name="content" class="form-control mb-2 mr-sm-2" id="newTask" placeholder="Type here...">
                            </div>
                            <button type="submit" class="btn btn-primary mb-2">Create</button>
                        </form>
                    </div>
                    <div class="btn-group">
                        <button type="button" class="btn btn-outline-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <svg class="bi bi-search" width="1.5em" height="1.5em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                <path fill-rule="evenodd" d="M10.442 10.442a1 1 0 0 1 1.415 0l3.85 3.85a1 1 0 0 1-1.414 1.415l-3.85-3.85a1 1 0 0 1 0-1.415z"/>
                                <path fill-rule="evenodd" d="M6.5 12a5.5 5.5 0 1 0 0-11 5.5 5.5 0 0 0 0 11zM13 6.5a6.5 6.5 0 1 1-13 0 6.5 6.5 0 0 1 13 0z"/>
                            </svg>
                        </button>
                        <form class="dropdown-menu p-3 dropdown-menu-right" style="width: 300px;" action="{% url 'todoapp:search' %}" method="get">
                            <div class="form-group">
                                <label for="newTask">Search</label>
                                <input type="search" name="search" class="form-control mb-2 mr-sm-2" placeholder="Type here...">
                            </div>
                            <button type="submit" class="btn btn-primary mb-2">Submit</button>
                        </form>
                    </div>
                </div>

            </div>
        </div>
        <div class="row ml-0">
            <p>You have {{ todo_items.count }} uncompleted task(s).</p>
        </div>
        <div class="row mt-2">
            <div class="col">
                <h3>Inbox</h3>
                <ul class="list-group">
                    {% for todo_item in todo_items %}
                        <li class="list-group-item list-group-item-action d-flex justify-content-between">{{ todo_item.text }}
                            <div class="btn-group">
                                <form action="{% url 'todoapp:finish' todo_item.id %}" method="post">
                                    {% csrf_token %}
                                    <button type="submit" class="btn btn-sm btn-outline-success mr-2">Complete</button>
                                </form>
                                <form action="{% url 'todoapp:delete' todo_item.id %}" method="post">
                                    {% csrf_token %}
                                    <button type="submit" class="btn btn-sm btn-outline-danger">Delete</button>
                                </form>
                            </div>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>

        {% if completed_times %}
            <div class="row mt-4 mb-4">
                <div class="col">
                    <h3>Completed tasks</h3>
                    <ul class="list-group">
                        {% for item in completed_times %}
                            <li class="list-group-item list-group-item-action list-group-item-light">{{ item.text }}
                                <div class="float-right">
                                    <form action="{% url 'todoapp:delete' item.id %}" method="post">
                                        {% csrf_token %}
                                        <button type="submit" class="btn btn-sm btn-outline-danger">Delete</button>
                                    </form>
                                </div>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        {% endif %}
    {% endblock %}
</body>
</html>

todoapp/templates/todoapp/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Sign up</title>
</head>
<body>
    <h1>Create a new account</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Sign up">
    </form>
</body>
</html>

todoapp/templates/todoapp/result.html
{% extends 'base.html' %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}Search results{% endblock %}
</head>
<body>
    {% block content %}
        <div class="row mt-4">
            <div class="col">
            <h3>Search result(s) of "{{ query_string }}"</h3>
            <div class="list-group list-group-flush mt-2">
                {% for task in found_tasks %}
                    <div class="list-group-item mb-1">
                        <h5>{{ task.text }}</h5>
                        <small>Status:
                            {% if task.done %}
                                Completed
                            {% else %}
                                Uncompleted
                            {% endif %}
                        </small>
                    </div>
                {% endfor %}
            </div>
    {% endblock %}
</body>
</html>

users/templates/users/login.html
{% extends 'base.html' %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Sign in</title>
    {% block title %}Sign in{% endblock %}
</head>
<div>
    {% block content %}
        <div class="row mt-4">
            <div class="mx-auto" style="width: 200px;">
                <h2>Sign in</h2>

                <form action="{% url 'users:login' %}?next={% url 'todoapp:list' %}" method="post">
                    {% csrf_token %}
                    {% include 'bs4_form.html' with form=form %}
                    <button type="submit" class="btn btn-primary">Sign in</button>
                </form>

            </div>
        </div>
    {% endblock %}
</body>
</html>

users/templates/users/signup.html
{% extends 'base.html' %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Sign up</title>
    {% block title %}Sign up{% endblock %}
</head>
<body>
    {% block content %}
        <div class="row mt-4">
            <div class="mx-auto" style="width: 600px;">

                <h2>Create a new account</h2>

                <form action="" method="post">
                    {% csrf_token %}
                    {% include 'bs4_form.html' with form=form %}
                    <button type="submit" class="btn btn-primary">Sign up</button>
                </form>

            </div>
        </div>
    {% endblock %}
</body>
</html>